### ISSUE TITLE
spike: data / file storage

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/irs#44]
Once we have files created they'll need to be stored for IRS regulations. These will need to be encrypted as well. A good candidate for storage would be compatible cloud services. 

Metadata (key/value pairs) will likely need to be searchable / stored alongside this.

What does this process look like? Does it live in this service? How would these be referenced by the Customers service?

**Comment by adamdecaf** [comment]
I wonder if storing the JSON forms of files in a database would be the best option. It would need to support querying deep into the documents for metadata search (think `customerID`, or arbitrary k/v filtering).

We should store the generated files so we have exact copies of what end-users and the IRS get as those would need to be given if the IRS requests.

**Comment by mfdeveloper508** [comment]
Now irs project is supported main logic for creating, parsing, validating.
There is no logic for store, deep query, customer.

I think that there is another project for customer.
so we can add customer ID only without management of customer easily.

it seems that storing the JSON forms of files in a database isn't the best option.
we have database connection in this project yet, we can store the file in database.
of course we should do modeling for some records, will support other features using this structure.
but using json file as input when create irs file is better. because user need to add many fields.

I think that the issue isn't question, is request.

so for this issue, we should do
- file store with database
- file indexing by customer id and any index (database record index or other index)
- update cli and endpoint

RISK:
I am not sure how would these be referenced by the customers service.
there are 2 options:
- using customers service package
  in this case we need to access to customer database too.
- using API endpoints

I want to discuss about these logics

**Comment by adamdecaf** [comment]
Apologies @mfdeveloper508 I saw this after we chatted in Slack. We're going to just store the documents and their JSON form first. Advanced querying can come later, but we'll have the calling service store that metadata for now.
